[build]
  # 빌드 명령어
  command = "python generate_static.py"
  # 배포할 디렉토리
  publish = "dist"
  
  # 환경 변수
  [build.environment]
    PYTHON_VERSION = "3.11"
    
[build.processing]
  skip_processing = false

# 리다이렉트 규칙
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/landing"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/notices"
  to = "/notices.html"
  status = 200

# 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self' http: https: data: blob: 'unsafe-inline'"

# 정적 파일 캐싱
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
