name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포를 방지하기 위한 동시성 설정
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 최소 필수 패키지만 설치하여 빌드 에러 방지
          pip install -r requirements-minimal.txt || pip install Flask==2.3.3 Jinja2==3.1.2 || true
          
      - name: Generate static files
        run: |
          mkdir -p static_build
          cp -r static/* static_build/ 2>/dev/null || true
          cp -r templates static_build/ 2>/dev/null || true
          cp *.html static_build/ 2>/dev/null || true
          # 기본 index.html 생성
          if [ ! -f static_build/index.html ]; then
            echo '<!DOCTYPE html>
          <html lang="ko">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>BLH COMPANY</title>
              <meta http-equiv="refresh" content="0; url=https://github.com/JTY9410/BLH_HOMPAGE">
          </head>
          <body>
              <h1>BLH COMPANY</h1>
              <p>GitHub 저장소로 리디렉션 중...</p>
              <a href="https://github.com/JTY9410/BLH_HOMPAGE">GitHub 저장소 방문</a>
          </body>
          </html>' > static_build/index.html
          fi
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'static_build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
